### ISSUE TITLE
Alternative bell recipe suggestion

### ISSUE THREAD

**Issue by circuitsunfish** [Rainbow-Collective/rc_datapack#1]
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "#OO",
        "MGM",
        "MZS"
    ],
    "key": {
        "#": {
            "item": "minecraft:spruce_log"
        },
        "O": {
            "item": "minecraft:oak_log"
        },
        "M": {
            "item": "minecraft:mossy_stone_brick_wall"
        },
        "G": {
            "item": "minecraft:gold_block"
        },
        "Z": {
            "item": "minecraft:gold_nugget"
        },
        "S": {
            "item": "minecraft:stone_brick_wall"
        }
    },
    "result": {}
}

**Comment by pikeminnow** [comment]
Extant recipe: (profile view)
![image](https://user-images.githubusercontent.com/7891125/146686440-13903351-a69e-491a-a6cc-bc290f682462.png)
Proposed recipe: (anterior view)
![image](https://user-images.githubusercontent.com/7891125/146686451-5bfe1089-6f13-40d1-bd43-56d2b0f620f9.png)
