### ISSUE TITLE
Lab Grown Gems require 2+1/3 coal blocks.

### ISSUE THREAD

**Issue by circuitsunfish** [Rainbow-Collective/rc_datapack#11]
Per [minecraft documentation](https://minecraft.fandom.com/wiki/Lava_Bucket#Smelting) Lava should burn for 1000 seconds. The goal of lab gems is to be more expensive than the most expensive fuel source in the blast furnace, so the burn time of lab gems needs to be increased.

**Comment by rarmenia** [comment]
This is working as intended.
---
The intention for lab grown gems is that they would take more than one lava bucket to process, unfortunately we can't lock fuel types, so it taking a 2+1/3 coal blocks is also intended.

This process should not be cheap, and it costing an "annoying" amount of items is intended to encourage automation.
