### ISSUE TITLE
Slime is too easy to craft

### ISSUE THREAD

**Issue by mjsonofharry** [Rainbow-Collective/rc_datapack#6]
Slime is too easy to craft. It should require BOTH kelp and cactus. Egg should not be an option for it. Egg is too abundant and being able to craft slime from it trivializes slime acquisition.

If you really need to craft slime from eggs, you should require more eggs and an additional resource like kelp.

**Comment by circuitsunfish** [comment]
What about 8 eggs and a kelp

**Comment by mjsonofharry** [comment]
It still seems too trivial, but at least the kelp requires diversifying your resources.

**Comment by circuitsunfish** [comment]
Eggs and kelp/cactus are meant to provide Vegetarian and Vegan paths to access slime respectively.

**Comment by mjsonofharry** [comment]
I don't think that vegetarianism and veganism are an important enough gameplay path to justify making game balance decisions.

**Comment by circuitsunfish** [comment]
I can make it so that it's *either* Egg/kelp or Kelp/Cactus are valid, but supporting roleplay was an important reason for including craftable slime in the first place vs simply slaying slimes.

**Comment by mjsonofharry** [comment]
I don't see why we need to support vegan roleplay. Having two slightly different recipes is just confusing.

**Comment by circuitsunfish** [comment]
Given that Pandas can generate slime, I'm inclined to remove the purely plant-based option since there's now a no-harm option and there was not when this pack was created.

**Comment by mjsonofharry** [comment]
Can we just remove the vegan recipes.

**Comment by mjsonofharry** [comment]
It's confusing having so many redundant, similar ways to craft items.

**Comment by circuitsunfish** [comment]
Egg slime is the first thing I learned how to make in JSON so it is dear to my heart <3
